// Auto-generated by python_viz/generate_charts.py
const RETAIL_DATA = {
  kpis: {
    "total_revenue": 17743429.16,
    "total_orders": 805549,
    "unique_customers": 5878,
    "unique_products": 4623,
    "avg_order_value": 22.03,
    "top_category": "General Merchandise",
    "date_range": "Dec 2009 \u2013 Dec 2011"
},
  topProducts: {
    labels: ["Regency Cakestand 3 Tier", "White Hanging Heart T-Lig", "Paper Craft , Little Bird", "Manual", "Jumbo Bag Red Retrospot", "Assorted Colour Bird Orna", "Postage", "Party Bunting", "Medium Ceramic Top Storag", "Paper Chain Kit 50'S Chri"],
    revenues: [286486.3, 252072.46, 168469.6, 152340.57, 136980.08, 127074.17, 126563.04, 103880.23, 81416.73, 79594.33]
  },
  categoryRevenue: {
    labels: ["General Merchandise", "Gift & Stationery", "Home & Lighting", "Kitchen & Dining", "Home Decor", "Bags & Luggage", "Garden & Outdoors", "Toys & Games"],
    revenues: [6798632.38, 2343486.9, 1953991.43, 1912543.49, 1741265.22, 1724525.34, 570310.46, 362478.68]
  },
  monthlyTrends: {
    labels: ["2010-01", "2010-02", "2010-03", "2010-04", "2010-05", "2010-06", "2010-07", "2010-08", "2010-09", "2010-10", "2010-11", "2010-12", "2011-01", "2011-02", "2011-03", "2011-04", "2011-05", "2011-06", "2011-07", "2011-08", "2011-09", "2011-10", "2011-11", "2011-12"],
    revenues: [557319.06, 506371.06, 699608.99, 594609.19, 599985.79, 639066.58, 591636.74, 604242.65, 831615.0, 1036680.0, 1172336.04, 884591.89, 569445.04, 447137.35, 595500.76, 469200.36, 678594.56, 661213.69, 600091.01, 645343.9, 952838.38, 1039318.79, 1161817.38, 518210.79]
  },
  customerSegments: {
    labels: ["Regular", "High Value", "Occasional", "VIP"],
    counts: [2353, 2077, 778, 670]
  }
};
